dist: bionic
language: c
addons:
  apt:
    packages:
      - apache2-dev
      - libglib2.0-dev
      - liblasso3-dev
      - libssl-dev

script:
  - ./autogen.sh
  - ./configure CFLAGS=-Werror
  - make
  - make distfile
